[package]
name = "krill-kmip-ttlv"
version = "0.1.0-dev"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
edition = "2018"
description = "KMIP TTLV (de)serialization"
license = "BSD-3-Clause"

[dependencies]
hex = "0.4.3"
serde = "1.0.126"

[dev-dependencies]
pretty_assertions = "0.7.2"
serde_derive = "1.0.126"