[package]
name = "krill-kmip-ttlv"
version = "0.1.0-dev"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
edition = "2018"
description = "KMIP TTLV (de)serialization"
license = "BSD-3-Clause"
repository = "https://github.com/NLnetLabs/krill-kmip-ttlv/"
keywords = ["KMIP", "TTLV"]
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
exclude = ["/.github"]

[dependencies]
hex = "0.4.3"
log = "0.4.14"
serde = "1.0.126"

[dev-dependencies]
chrono = { version = "0.4.19", default-features = false }
pretty_assertions = "0.7.2"
serde_derive = "1.0.126"