name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against Rust 1.47.0 because in build.rs we say that is the oldest supported version.
        # Test against beta Rust to get early warning of any problems that might occur with the upcoming Rust release.
        # Order: oldest Rust to newest Rust.
        rust: [1.47.0, stable, beta]
        args: [
          "",
          "--no-default-features --features sync",
          "--no-default-features --features async-with-async-std",
          "--no-default-features --features async-with-tokio",
        ]
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Build
      run: cargo build --verbose ${{ matrix.args }} --locked

    - name: Run tests
      run: cargo test --verbose ${{ matrix.args }} --locked
